require('vlad.remap')
require('vlad.set')
require("vlad.autocommand")
require("vlad.commands")
require("vlad.lazy")
require("vlad.colors")
require("vlad.filetypes")
require("vlad.terminal")

require("vlad.file-jump")
require("vlad.nuget-info")
